---
title: "Nanna_Analysis"
author: "Nanna Katrin"
date: "06/05/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(ggplot2)
library(gridExtra)

```

## Combined

```{r combined}

dat_agelm <- combined_all %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

dat_agelm %>%  ggplot(aes(x = age)) + geom_point(aes(y = bad_conseq)) + geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Bad consequences of discussing mental health? (1/0)")


```

## Just 2016 


```{r 2016}
  
dat_agelm <- data2016_recode_rearrange %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

dat_agelm %>%  ggplot(aes(x = age)) + geom_point(aes(y = bad_conseq)) + geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Bad consequences of discussing mental health? (1/0)")


```




## Just 2018

```{r 2018}

dat_agelm <- data2018_recode %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

dat_agelm %>%  ggplot(aes(x = age)) + geom_point(aes(y = bad_conseq)) + geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Bad consequences of discussing mental health? (1/0)")


```
## All together


```{r allinone}

##2018
dat_agelm <- data2018_recode %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

p18 <- dat_agelm %>%  ggplot(aes(x = age)) + 
  geom_point(aes(y = bad_conseq), alpha = 0.5) + 
  geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Comfortable? (1/0)",
       title = "2018") + theme(title = element_text(size = 10))+
  theme_minimal()

##2016
dat_agelm <- data2016_recode_rearrange %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

p16 <- dat_agelm %>%  ggplot(aes(x = age)) + 
  geom_point(aes(y = bad_conseq), alpha = 0.5) + 
  geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Comfortable? (1/0)",
       title = "2016" ) + theme(title = element_text(size = 10))+
  theme_minimal()

##Both 2016 and 2018
dat_agelm <- combined_all %>% filter(age >=18 & age < 80, !(is.na(age)| is.na(comfortable_discussing_mh_with_supervisors)))

dat_agelm$bad_conseq <- ifelse(dat_agelm$comfortable_discussing_mh_with_supervisors == "Yes" | dat_agelm$comfortable_discussing_mh_with_supervisors == "Maybe", 1, 0)

dat_agelm <- dat_agelm %>% select(age, comfortable_discussing_mh_with_supervisors , bad_conseq)

age_model <- glm(bad_conseq ~ age, data = dat_agelm, family = binomial)

grid <- dat_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

pboth <- dat_agelm %>%  ggplot(aes(x = age)) + 
  geom_point(aes(y = bad_conseq), alpha = 0.5) + 
  geom_line(aes(y=pred), data = grid, color = "red", size = 1) +
  labs(y = "Comfortable? (1/0)",
       title = "Both 2016 and 2018") + theme(title = element_text(size = 10))+
  theme_minimal()

png("comfortable_talking_to_supervisors_vs_age.png", width = 700, height = 500)

plot <- grid.arrange(
  arrangeGrob(p16,p18, ncol=2),
  pboth,
  top = "\nComfort (0-1) in discussing mental health with supervisors as a function of age\n
  Difference across years\n"
  )

print(plot)
dev.off()

```

## Stigma Score model

```{r}

copy_combinedData <- combined_all

#quantify measures of stigma
copy_combinedData$difficulty_asking_for_mh_related_medical_leave <-
  recode(copy_combinedData$difficulty_asking_for_mh_related_medical_leave,
         "Very easy" = 1,
         "Somewhat easy" = 2,
         "Neither easy or difficult" = 3,
         "Somewhat difficult" = 4,
         "Very difficult" = 5)

copy_combinedData$comfortable_discussing_mh_with_coworkers <-
  recode(copy_combinedData$comfortable_discussing_mh_with_coworkers,
         "Yes" = 1,
         "Maybe" = 2,
         "No" = 3)

copy_combinedData$comfortable_discussing_mh_with_supervisors <-
  recode(copy_combinedData$comfortable_discussing_mh_with_supervisors,
         "Yes" = 1,
         "Maybe" = 2,
         "No" = 3)

copy_combinedData$willing_to_bring_up_mh_in_interview_y_n <-
  recode(copy_combinedData$willing_to_bring_up_mh_in_interview_y_n,
         "Yes" = 1,
         "Maybe" = 2,
         "No" = 3)

#generate total "stigma score" per person by summing quantified measures of
#stigma, and plot distribution of scores per gender per year

copy_combinedData <- copy_combinedData %>%
  filter(!is.na(gender), !is.na(age), !is.na(difficulty_asking_for_mh_related_medical_leave),
         !is.na(comfortable_discussing_mh_with_coworkers),
         !is.na(comfortable_discussing_mh_with_supervisors),
         !is.na(willing_to_bring_up_mh_in_interview_y_n)) %>%
  mutate(stigma_score = difficulty_asking_for_mh_related_medical_leave +
                               comfortable_discussing_mh_with_coworkers +
                               comfortable_discussing_mh_with_supervisors +
                               willing_to_bring_up_mh_in_interview_y_n)
```

```{r}

stigma_agelm <- copy_combinedData %>% filter(age >=18 & age < 80)

age_model <- lm(stigma_score ~ age, data = stigma_agelm)

grid <- stigma_agelm %>% data_grid(age) %>% add_predictions(age_model, type = "response")

png("stigma_vs_age.png", width = 700, height = 500)

stigma_plot <- stigma_agelm %>% ggplot(aes(x = age)) +
  geom_point(aes(y = stigma_score), position = "jitter", alpha = 0.5, color = "coral") + 
  geom_line(aes(y=pred), data = grid, color = "black") + 
  theme_minimal()+
  labs(title = "Relationship between Stigma Score and Age",
       y = "Stigma Score",
       x = "Age")+ theme(plot.title = element_text(hjust = 0.5))

print(stigma_plot)
dev.off()


```




